### PR TITLE
fix: Remove dense property from header buttons

### PR DESCRIPTION
**Pull request by Ryan-Thomas**
+ No change in functionality

#### Pre-Submission Checklist:

- [x] Your pull request targets the `master` branch of calltocode.org
- [x] Your branch is updated with the latest changes on `master`
- [x] Your branch passes linting, building and all new and existing tests with command `yarn test`
- [N/A] The story that this pull request addresses is referenced above by ID

#### Post-Submission Checklist:

- [x] Address any reviews on your pull request, as it will not be merged until it is approved
- [x] Your branch has no conflicts with `master` (find this out at the bottom of your pull request)

#### Description of Changes:

Removed dense property from header buttons to remove errors being logged in redux. It seems that this property was added by mistake because the documentation of Material-UI lists dense as a potential class name and not a property.

Making the fix didn't seem to affect the functionality in any way.

### CODE REVIEW

**Comment by bbmoz** [comment]
You can update the version here https://github.com/CodeForSocialGood/calltocode.org/blob/master/package.json#L53. Make sure to commit the updated `yarn.lock` file as well. After these changes, let's go ahead and merge it in!

**Comment by Ryan-Thomas** [comment]
How do I update the version? What should I change it to? 

I tried yarn upgrade material-ui and nothing happened, so I'm not sure what I should change the line 
`"material-ui": "^1.0.0-beta.29",` 
to

**Comment by bbmoz** [comment]
One way is to run `yarn remove material-ui` and then `yarn add material-ui`. This should update the `package.json` and `yarn.lock` file with the latest version.

**Comment by timdavish** [comment]
So the problem is we're using the material ui beta (which is what they're currently putting all their effort in), so it'd be something like `npm install --save material-ui@next`

**Comment by bbmoz** [comment]
@Ryan-Thomas Please resolve conflicts, so we can move forward with merging in this PR, thanks!

**Comment by bbmoz** [comment]
This PR is over 20 days old. I am closing this.

**Pull request closed without merging**
