### PR TITLE
Feature/#154303579 - Make all <h1>'s consistent across pages

### PR DESCRIPTION
**Pull request by timdavish**
[#154303579]

### CODE REVIEW

**Comment by mattwills8** [comment]
Looks good, looks like you got them all. 

Only thing is why is the new password form being deleted int he second commit? Is that not something we need?

**Comment by timdavish** [comment]
Oh yeah.. I should have noted that
It is duplicate code that isn't used; the form got moved into the ForgotPasswordForm folder

**Comment by mattwills8** [comment]
ah okay cool, merging now then

**Comment by mattwills8** [comment]
actually only other thing I thought was maybe we should move it into a main.scss file and include that in index.js or something. just so we aren't mixing css and scss, could be confusing right?

**Comment by timdavish** [comment]
the entire index.css file?

**Comment by mattwills8** [comment]
yeah, was thinking just stick it in a main.scss in the scss folder and import it into index.js. Just to keep all the global styles together in one folder :)

**Comment by timdavish** [comment]
I do agree with that logic. I'm just not sure what's going to happen with styling now that we're introducing material ui which prefers to use jss for it's components

Check out @sexta13 's PR [here](https://github.com/CodeForSocialGood/calltocode.org/pull/133/files#diff-d668fe3ecadcafd2bee7dd9a9c7a00cc) for an example of what I'm talking about

**Comment by timdavish** [comment]
Let's make a chore for that just to keep it separate from this PR

How does that sound?

**Comment by mattwills8** [comment]
yeah all good man, we can reasses after we've integrated the material ui stuff

**Comment by timdavish** [comment]
Actually I do think that regardless we should move it into a .scss as the global styles don't have much if anything to do with the MUI components!

**Comment by mattwills8** [comment]
haha okay, I'll make that change quick

**Comment by mattwills8** [comment]
found those h1s, there's a few .scss files which just have global h1 styling so that gets included everytime the one of the files is imported. these need to be made into local classes, otherwise these h1s (which I assume are meant to be local) are affecting all h1s globally

**Comment by mattwills8** [comment]
I'll do that as a separate chore

**Comment by timdavish** [comment]
yep, I just figured that out as well
good find. that should be changed for sure.

**Comment by mattwills8** [comment]
yeah we'll need to be careful of that, maybe something to warn the team about

**Pull request merged**
