### PR TITLE
Feature/#155111468 - Visitor sees Landing Page (Section D)

### PR DESCRIPTION
**Pull request by Djgodwin**
[#155111468]

#### Pre-Submission Checklist:

- [x] Your pull request targets the `master` branch of calltocode.org
- [x] Your branch is updated with the latest changes on `master`
- [x] Your branch passes linting, building and all new and existing tests with command `yarn test`
- [x] Your branch passes the end-to-end tests with command `yarn e2e`
- [x] The story that this pull request addresses is referenced above by ID

#### Post-Submission Checklist:

- [ ] Your branch has no conflicts with `master` (find this out at the bottom of your pull request)
- [ ] Address any reviews on your pull request, as it will be unable to be merged until it is approved

#### TODO:
After updating my local files to match the master branch, I now get an error when attempting to access the landing page.
```
{ UnauthorizedError: No authorization token was found
    at middleware (/home/damon/workspace/calltocode.org/node_modules/express-jwt/lib/index.js:76:21)
    at handleReturn (/home/damon/workspace/calltocode.org/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /home/damon/workspace/calltocode.org/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/layer.js:95:5)
    at /home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:335:12)
    at next (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:174:3)
    at router (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:317:13)
    at /home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:335:12)
  name: 'UnauthorizedError',
  message: 'No authorization token was found',
  code: 'credentials_required',
  status: 401,
  inner: { message: 'No authorization token was found' } }
GET /api/applications/notifications 401 44.632 ms - 2021
{ UnauthorizedError: No authorization token was found
    at middleware (/home/damon/workspace/calltocode.org/node_modules/express-jwt/lib/index.js:76:21)
    at handleReturn (/home/damon/workspace/calltocode.org/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /home/damon/workspace/calltocode.org/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/layer.js:95:5)
    at /home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:335:12)
    at next (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:174:3)
    at router (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:317:13)
    at /home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/damon/workspace/calltocode.org/node_modules/express/lib/router/index.js:335:12)
  name: 'UnauthorizedError',
  message: 'No authorization token was found',
  code: 'credentials_required',
  status: 401,
  inner: { message: 'No authorization token was found' } }
GET /api/applications/notifications 401 3.287 ms - 2021
GET /favicon.ico 200 0.764 ms - 412
```

### CODE REVIEW

**Comment by mithuns** [comment]
Whats the solution for this ?  I am also seeing this now.

**Comment by sexta13** [comment]
I can fix that Error in [PR 155](https://github.com/CodeForSocialGood/calltocode.org/pull/155). I know what it is...

**Comment by bbmoz** [comment]
PR 155 has been merged.

**Comment by sexta13** [comment]
replaced by https://github.com/CodeForSocialGood/calltocode.org/pull/209

**Pull request closed without merging**
